[package]
name = "moth"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.37", features = ["derive"] }
hotwatch = "0.5.0"
katex = "0.4.6"
tiny_http = "0.12.0"
tungstenite = "0.26.2"
